### ISSUE TITLE
Ícone indicativo de processo recebido pelo Barramento do PEN

### ISSUE THREAD

**Issue by guilhermeadc** [supergovbr/mod-sei-pen#12]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
O usuário acessa o SUPER e deseja ter a informação dos processos recebidos em sua unidade que vieram do Barramento de Serviços. Os processos oriundos de outro órgão via barramento de serviços não são destacados e os mesmos precisam ser priorizados em boa parte das situações. Usuário sente necessidade de ter um indicativo visual para tal tipo de processo. 

-----

**Descreva a solução que você gostaria**
Adicionar um ícone informativo ao processo indicando que este foi recebido externamente pelo Barramento de Serviços do PEN. 
Tal ícone deverá ser visível na árvore do processo e, principalmente, na página de controle de processo.  Deve conter opção de acessibilidade nos ícones conforme outros tipos de processo.

Ícone sugerido share-node light https://fontawesome.com/icons/share-nodes?s=light&f=classic

-----

**Descreva alternativas que você considerou**
N/A

-----

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.

Item 2.5 e 2.6 do manual
https://super-docs-kjansdxkansds.readthedocs.io/pt_BR/latest/Iniciando_operacoes.html#tela-de-controle-de-processos

**Comment by yuribitu** [comment]
Link para o repositorio do Código fonte:
https://github.com/supergovbr/mod-sei-pen

**Comment by caduvieira** [comment]
Os métodos montarIconeControleProcessos e montarIconeProcesso são os pontos de extensão do SUPER

**Comment by guilhermeadc** [comment]
Prezados, 

Durante os testes desta funcionalidade, foram identificados dois pequenos problemas que precisam ser ajustados antes de serem aceitos e incorporados ao mod-sei-pen.

1) O ícone indicativo de processo recebido pelo Tramita.gov.br está se repetindo inúmeras vezes, 1 para cada trâmite já realizado pelo processo, conforme demonstrado abaixo.
![image](https://user-images.githubusercontent.com/4326504/233872119-a772055e-4baa-404e-b07c-1a8a5bb36f85.png)

O comportamento correto deveria ser a apresentação de apenas 1 ícone indicando que o último recebimento.

2) Quando este processo é enviado para outra unidade, o ícone continua aparecendo, indicando que o processo chegou pelo Tramita.gov.br, fato que não é verdade já que ele foi recebido proveniente de outra unidade.
![image](https://user-images.githubusercontent.com/4326504/233872263-edf370b7-5cd8-4246-9cbf-d2a15d4677f7.png)

O comportamento esperado neste caso em que um processo recebido pelo Tramita.gov.br e depois enviado para outra unidade seria não apresentar o ícone já que o mesmo foi recebido na unidade TESTE_1_1 por envio simples de uma unidade para outra.

Para reproduzir este segundo caso, os seguintes passos devem ser realizados:
1) Enviar um processo do órgão 1 para o órgão 2 
2) No órgão 2, identificar o processo e verificar se o ícone está aparecendo (comportamento esperado)
3) Enviar o mesmo processo para a unidade SEI TESTE_1_1
4) Mudar o contexto da unidade no SEI de TESTE para TESTE_1_1
5) Identificar o processo e verificar que o ícone nâo está sendo apresentado (comportamento esperado já que ele foi recebido de outra unidade do SEI, e nâo do Tramita.gov.br.

**Comment by euviniciusmendonca** [comment]
Aguardando o novo ícone para incluir na issue @pedrohpms @caduvieira.

**Comment by pedrohpms** [comment]
@caduvieira, já estão prontos e aprovados. Qual o formato para up no SEI.

**Comment by gicastephanou** [comment]
Prezados,
Como já existe uma outra issue com o mesmo objeto (#226), encerraremos esta issue.
