### ISSUE TITLE
Botão "Cancelar Tramitação Externa" somente ser exibido para a Unidade que acionou o "Envio Externo de Processo"

### ISSUE THREAD

**Issue by neijobson** [supergovbr/mod-sei-pen#126]
O botão "Cancelar Tramitação Externa" está sendo exibido sobre o processo PARA TODOS no SEI, independentemente do processo já ter tramitado pela Unidade, se o processo está aberto na Unidade e de ter sido ou não a Unidade de fato demandante do "Envio Externo de Processo".

Sugerimos que revisem as regras de negócio sobre a exibição do botão "Cancelar Tramitação Externa" para ser exibido SOMENTE sobre o processo Aberto na Unidade de fato demandante do "Envio Externo de Processo", para evitar ingerência indevida de outras Unidades cancelando o Envio Externo sem ter sido a Unidade que acionou o envio.

**Comment by caduvieira** [comment]
Já agendado para correção. Indicação da versão que será publicado será comunicado em breve.

**Comment by Mauro1706** [comment]
feito no PR https://github.com/supergovbr/mod-sei-pen/pull/204
