### ISSUE TITLE
Barra de rolagem nas mensagens de erro nos trâmites

### ISSUE THREAD

**Issue by fe-neto** [supergovbr/mod-sei-pen#134]
Após a atualiação do SEI4 a janela de trâmite não mostra a mensagem de erro completa no modal de envio de processos.

**Comment by caduvieira** [comment]
![Screenshot 2022-10-31 at 16-32-29 SEI - Processo](https://user-images.githubusercontent.com/3831408/199094262-d075c0f5-8a0d-43b6-a13a-b61193eb0a59.png)
