### ISSUE TITLE
Erro Segmentation Fault e Disco Cheio ao receber determinados processos

### ISSUE THREAD

**Issue by marlinhares** [supergovbr/mod-sei-pen#143]
**Descreva o erro**
No Ministério da Economia foi identificado que ao receber determinados documentos acontece Segmentation Fault

-----

**Para reproduzir**
Como os documentos problemáticos são restritos não podemos disponibilizar aqui.
Contactar a Central de Atendimento e pedir para acionar a equipe técnica responsável pelo módulo do Barramento solicitando uma amostra do documento problemático

Ao receber o documento aparece segmentation fault.
Em alguns casos isso pode gerar um dump da memoria do processo no disco e ao longo dos dias o disco estoura fazendo parar o processo de recebimento

**Comment by caduvieira** [comment]
No SEI 4 não é afetado mais pois não se usa essa função pref_replace?

**Comment by marlinhares** [comment]
Muito importante. Eu não sei informar se o ajuste no valor desse atributo pode "afrouxar" a segurança da validação do XSS no caso.
Como o problema não acontece nos pacotes instalados do SEI4 (tudo indica q foi corrigido eventual bug) eu recomendaria inicialmente não alterar esse atributo caso não tenha certeza que ele pode relaxar a validação XSS. E usá-lo apenas em casos de excessão e temporariamente.

Ou altere a versão do pacote PCRE ou migre para o SEI4

**Comment by caduvieira** [comment]
Tem razão. https://bugs.php.net/bug.php?id=76276 informa que foi corrigido ao mudar para o PCRE2 no PHP 7.3. Obrigado! :+1:
