### ISSUE TITLE
Melhoria Interface - Processos recebidos pelo Barramento

### ISSUE THREAD

**Issue by euviniciusmendonca** [supergovbr/mod-sei-pen#145]
-- Viabilidade------------------------------------------------------------------------------------------------------------------------------------

Atualmente, na interface do SEI não existe nenhum recurso visual que demonstra que um processo foi recebido pelo Barramento de Serviços do PEN.  O objetivo é verificar a viabilidade de evoluir a interface para contemplar de alguma forma indicativo que o processo foi recebido pelo barramento, bem como algum indicativo para reforçar a importância do processo ser devolvido também pelo Barramento.

A CGPRO possui uma meta de trâmites e economia anual. Atualmente, nós estamos abaixo da meta. Queremos evoluir a interface para estimular a utilização da solução.

**Comment by guilhermeadc** [comment]
Esta implementação foi programada para a versão 3.1.14 do módulo que está em andamento neste momento.

**Comment by caduvieira** [comment]
Duplicado do #12
