### ISSUE TITLE
Erro em trâmites SEI x SUPERBR

### ISSUE THREAD

**Issue by filipegomes1** [supergovbr/mod-sei-pen#148]
Processos 00768.000003/2021-12 e 00768.000021/2022-77 tramitados da AGU-SUPERBR para SEI-ANCINE e depois devolvido normalmente, mas quando a AGU tenta enviar para ANCINE, informa que "Já existe um processo utilizando o número de protocolo".
Não conseguimos identificar o porquê dessa inconsitência. 

![image](https://user-images.githubusercontent.com/71085632/165812447-2e237bcc-a12d-41f8-a39c-7810e028024a.png)
![image](https://user-images.githubusercontent.com/71085632/165812570-31782185-4e40-423d-aeb9-794da398075f.png)

**Comment by guilhermeadc** [comment]
@filipegomes1 , poderia verificar se este problema ainda ocorre e se trata de um erro do módulo?

**Comment by guilhermeadc** [comment]
Avaliando o cenário descrito, este problema ocorreu devido a uma falha na versão da integração implementada no sistema SUPER.GOV.BR. Demanda será fechada.
