### ISSUE TITLE
Verificação de compatibilidade do banco está verificando o módulo 

### ISSUE THREAD

**Issue by caduvieira** [supergovbr/mod-sei-pen#152]
**Descreva o erro**
A verificação da compatibilidade do banco está verificando o módulo e não o banco.
https://github.com/spbgovbr/mod-sei-pen/blob/master/src/PENIntegracao.php#L629

-----

**Para reproduzir**
N/A

-----

**Comportamento esperado**
Que se fosse verificado o banco e não o módulo

-----

**Screenshots**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema. Sugerimos o uso do Peek (linux) ou ScreenToGif (windows) para captura.

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Ambiente: [nome e/ou endereço do sistema em que o erro foi identificado]
 - Versão do sistema: [ex: 1.0.1]
 - Navegador: [ex. chrome, safari]
 - Perfil do Usuário: [ex: colaborador, externo, coordenador, administrador, etc.]

-----

**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
Adicione o log de erros registrado pelo sistema. Verifique o log registrado no servidor, através da funcionalidade Infra> Log

**Comment by guilhermeadc** [comment]
Issue será fechada devido a mudança na lógica de verificação de combatibilidade de banco de dados por não ser todas as versões que necessitam mudanças no banco de dados.
