### ISSUE TITLE
Melhoria no Script de Verificação de Instalação do Módulo

### ISSUE THREAD

**Issue by marlinhares** [supergovbr/mod-sei-pen#18]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Ao tentar usar o script de verifica_instalacao_modulo_pen.php não é capaz de identificar que o gearman está fora do ar e trava ao invés de indicar a falta do gearman. 

-----

**Descreva a solução que você gostaria**
Que o script informe que está tentando se conectar com o gearman e o mesmo está fora do ar depois de ocorrer o timeout.

-----

**Descreva alternativas que você considerou**
N/A

-----

**Contexto adicional**
Usar comando de verificação conforme manual de instalação https://github.com/supergovbr/mod-sei-pen/blob/master/docs/INSTALL.md#110-verifica%C3%A7%C3%A3o-e-testes-da-instala%C3%A7%C3%A3o-do-m%C3%B3dulo

configurei um servidor e uma porta de gearman.
Mas esqueci de subir o gearman
Ao rodar o script de verificação ele trava em um dos passos e hanga.
Aqui pra mim não destravou, portanto se possível, antes de verificar o gearmand, exibir uma mensagem do tipo:
--- servidor xxx:porta identificados para o gearmand, tentando proceder com a conexão ----

Desta forma mesmo se der problema o tecnico vai saber onde parou, sem precisar olhar no codigo

abcs

**Comment by caduvieira** [comment]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Ao tentar usar o script de verifica_instalacao_modulo_pen.php não é capaz de identificar que o gearman está fora do ar e trava ao invés de indicar a falta do gearman. 

-----

**Descreva a solução que você gostaria**
Que o script informe que está tentando se conectar com o gearman e o mesmo está fora do ar depois de ocorrer o timeout.

-----

**Descreva alternativas que você considerou**
N/A

-----

**Contexto adicional**
Usar comando de verificação conforme manual de instalação https://github.com/supergovbr/mod-sei-pen/blob/master/docs/INSTALL.md#110-verifica%C3%A7%C3%A3o-e-testes-da-instala%C3%A7%C3%A3o-do-m%C3%B3dulo

**Comment by caduvieira** [comment]
Não vi o PR. Voltando para A fazer.

**Comment by higodf** [comment]
Não nenhum novo commit para inferir que houve correção do erro anteriormente reportado.
