### ISSUE TITLE
Erro de hash nos documentos

### ISSUE THREAD

**Issue by higodf** [supergovbr/mod-sei-pen#183]
**Descreva o erro**
Ao mudar a sigla do órgão o título dos documentos estão sendo alterados. Nesse cenário o módulo entende que houve alteração no documento e apresenta mensagem de erro informando que o hash foi alterado.

-----

**Comportamento esperado**
Que o módulo consiga tramitar o processo pois não ouve alteração no documento mas sim mudança na sigla do órgão

**Comment by caduvieira** [comment]
Essa sigla faz parte do corpo do documento ou é somente do rodapé ou cabeçalho do mesmo?

**Comment by higodf** [comment]
> Essa sigla faz parte do corpo do documento ou é somente do rodapé ou cabeçalho do mesmo?

faz parte do corpo do documento.
