### ISSUE TITLE
Melhoria no script de verificação da instalação e configuração do German

### ISSUE THREAD

**Issue by marlinhares** [supergovbr/mod-sei-pen#19]
Instalei o supervisor e o gearman.
subi os 2 e esqueci de configurar a porta e o servidor no arquivo de config do PEN

O script de verificação informou que estava td certo, mas eles ficam dando erro pois o supervisor n consegue jogar pra fila.
Sendo assim sugiro uma possível mensagem no script de instalacao que será mostrada sempre:
--- verificando se há configuraçao setada de gearman no arquivo de config do modulo ----
--- não foi encontrada configuracao, o módulo não irá usar o gearman (caso nao encontre na config)
--- encontrada a config do servidor porta xxx:4730. Tentando proceder com a conexão

vlw

**Comment by higodf** [comment]
Conforme msg acima não há PR para validação.

**Comment by guilhermeadc** [comment]
Considerando as implementações realizadas recentemente no mod-sei-pen, os comportamentos sugeridos nesta demanda foram adicionados corretamente. As melhorias comentadas anteriormente foram disponibilizadas na versão 3.2.3 do mod-sei-pen.
