### ISSUE TITLE
Modificar tipo de dados do campo ticket_envio_componentes para varchar

### ISSUE THREAD

**Issue by guilhermeadc** [supergovbr/mod-sei-pen#190]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Atualmente, o módulo está armazenando o campo ticket_envio_componentes como um CLOB em Oracle, impedindo que a biblioteca de pesquisa utilizada pelo SEI possa fazer consultas filtrando por este campo. Como este campo serve unicamente para registrar o identificador do ticket para envio de componentes digitais, não existe a necessidade de ser um campo CLOB.

```php

$objMetaBD->criarTabela(array(
 'tabela' => 'md_pen_tramite',
 'cols' => array(
 //....
 'ticket_envio_componentes' => array($objMetaBD->tipoTextoGrande(), PenMetaBD::SNULLO),
 //....
```

-----

**Descreva a solução que você gostaria**
Mudar campo 'ticket_envio_componentes' da tabela md_pen_tramite para varchar, em vez de um campo texto sem limite (CLOB em Oracle), para permitir filtros por esta informação e otimizar o armazenamento de dados do mod_sei_pen.

-----

**Descreva alternativas que você considerou**
N/A

-----

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.

**Comment by guilhermeadc** [comment]
Deverá ser testado a execução do script de atualização nas bases Postgresql, MySQL, Oracle, SqlServer

**Comment by guilhermeadc** [comment]
Sugiro utilizar a sequencia do comando abaixo para resetar o ambiente e já testar a execução do script:

`make destroy && make config base=mysql && make up && make update`

**Comment by MatheusMarques80** [comment]
Pull request: https://github.com/supergovbr/mod-sei-pen/pull/229
