### ISSUE TITLE
Processo aberto na unidade Externa - Versão 4.0.9

### ISSUE THREAD

**Issue by RafaelCostaCorrea** [supergovbr/mod-sei-pen#199]
Ao realizar a tramitação pelo barramento PEN  o processo continua aberto na unidade de recebimento Externo. Achei outro reporte referente à versão 4.0.6 do SEI, mas estou com a versão 4.0.9.

**Comment by caduvieira** [comment]
Qual a versão do módulo que está sendo usado? Poderia preencher o template da issue para mais informações?

**Comment by RafaelCostaCorrea** [comment]
Opa, boa tarde! Desculpa a demora e por não inserir no template. Notei que havia uma atualização do módulo. Atualizei e está funcionando perfeitamente. Estamos utilizando o SEI 4.0.9 e módulo PEN 3.2.0.
