### ISSUE TITLE
Erro de formatação de campos na página d envio de processos em Lote

### ISSUE THREAD

**Issue by guilhermeadc** [supergovbr/mod-sei-pen#200]
**Descreva o erro**
Os campos da página de envio externo de processos em lote estão desformatados:
- A lista de processos selecionados apresenta está pequena, estando visível apenas o primeiro processo
- Demais campos com espaçamento errado

----
**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

-----

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

-----

**Screenshots**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema. Sugerimos o uso do Peek (linux) ou ScreenToGif (windows) para captura.

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: [ex: 1.0.1]
 - Navegador: [ex. chrome, safari]
 - Perfil do Usuário: [ex: colaborador, externo, coordenador, administrador, etc.]
 - Banco de dados: [MySQL, SQLServer, Oracle ou PostgreSQL]
-----

**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
Adicione o log de erros registrado pelo sistema. Verifique o log registrado no servidor, através da funcionalidade Infra> Log

**Comment by Mauro1706** [comment]
Resolvido no PR https://github.com/supergovbr/mod-sei-pen/pull/206
