### ISSUE TITLE
Testar no módulo PEN na versão 4.0.8 e 4.0.9

### ISSUE THREAD

**Issue by caduvieira** [supergovbr/mod-sei-pen#203]
É necessário testar o módulo na versão SEI 4.0.8 e 4.0.9.

E ajustar os testes caso algum ajuste nos testes seja necessário. 

Os testes devem ser realizados nas três bases de dados.  MySql, SQLServer e Oracle.

**Comment by mrglaydson** [comment]
VerificardorInstalacaoRN

**Comment by marlinhares** [comment]
#207
