### ISSUE TITLE
Inconsistência na situação do processo tramitado quando ocorre erro no armazenamento do recibo de conclusão do trâmite

### ISSUE THREAD

**Issue by guilhermeadc** [supergovbr/mod-sei-pen#215]

**Comment by guilhermeadc** [comment]
A tratativa deverá ser implementada na classe ReceberProcedimentoRN, método enviarReciboTramiteProcesso

**Comment by Mauro1706** [comment]
Feito o PR https://github.com/supergovbr/mod-sei-pen/pull/220
