### ISSUE TITLE
Viabilidade de Alterar o nome da Unidade EXTERNO

### ISSUE THREAD

**Issue by euviniciusmendonca** [supergovbr/mod-sei-pen#223]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Que os manuais de instalação sejam atualizados para indicar origem e usuário com maior clareza no histórico de andamento do processo no SPE. Atualmente o do ME, por exemplo, vem como Unidade Externo e Usuário SEI.
 
![download](https://user-images.githubusercontent.com/60577185/219666654-197dc1be-54bc-4254-8b13-692157029d93.png)

-----

**Descreva a solução que você gostaria**
Alterar o nome da unidade e do usuário para deixar claro o recebimento do processo por meio do Tramita.GOV.BR.

-----

**Comment by guilhermeadc** [comment]
Demanda concluída com a atualização da documentação de instalação do módulo.
