### ISSUE TITLE
Documento movimentado para novo processo e depois movimentado novamente para o processo original

### ISSUE THREAD

**Issue by euviniciusmendonca** [supergovbr/mod-sei-pen#228]
**Descreva o erro**
Um documento externo foi movimentado para outro processo e depois movimentado novamente para o processo de origem. Ao tentar trâmite externo, ocorre um erro.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Criar dois processos por meio da funcionalidade Iniciar Processos;
2. Em um dos processos criar um documento do tipo externo;
3.  Movimentar o documento de um processo para outro;
4.  No segundo processo, movimentar o documento para o processo original;
5.  O documento estará duplicado no processo, sendo a primeira uma referência a primeira movimentação;
6.  Ao tentar tramitar o processo por meio do Tramita.GOV.BR gera um erro( ver a imagem).

-----

**Comportamento esperado**
Verificar a viabilidade de ignorar a referência do arquivo movimentado inicialmente para o outro processo para dar continuidade ao trâmite ou emitir uma mensagem mais amigável.

-----

**Screenshots**
![image](https://user-images.githubusercontent.com/60577185/221944836-746a32cf-1c1d-46ef-8794-22e30fe8bdd0.png) 

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: Qualquer um
 - Navegador: Qualquer um
 - Perfil do Usuário: Administrador + Básico( confirmar se o tem recurso para movimentar o processo)
 - Banco de dados: Qualquer um
-----

**Informações adicionais**
N/A
-----
**Log de Erros**
Não se aplica.

**Comment by guilhermeadc** [comment]
Durante os testes de validação do funcionamento desta implementação, foi identificado falha na lógica de tratamento para documentos movimentados dentro do processo.

Conforme testes demonstrados abaixo, foi verificado que o documento movido do processo na origem não está sendo enviando com o registro que foi removido do processo. O que está ocorrendo é que este documento está chegando duplicado no destino. O resultado esperado deveria indicar que o documento movido no processo de origem foi recebido como cancelado no destino.

Para reproduzir o problema, os passos da seção "Para Reproduzir" desta Issue deverá ser executado.

Como pode ser visto nas imagens de teste abaixo, o processo na origem possui 4 documentos distintos, sendo o segundo movido para o processo B, e o quarto documento sendo o movido do processo B para A.

Processo original do órgão 1:
![image](https://user-images.githubusercontent.com/4326504/233888791-b34b0782-0485-48f8-ad4a-b80a21111641.png)

Processo recebido no órgão 2:
![image](https://user-images.githubusercontent.com/4326504/233889000-5b4e5265-3659-4328-bf8b-ea611dbd00a9.png)
