### ISSUE TITLE
Versão 3.2.2 e 3.2.3 não compatíveis com a versão 4.0.9 do SEI

### ISSUE THREAD

**Issue by rodpinst** [supergovbr/mod-sei-pen#234]
Prezados,

   Estamos atualizando a nossa instalação do SEI para a versão 4.0.9 do SEI Core. Contudo ao tentarmos atualizar o módulo do PEN para a versão 3.2.3 e depois para 3.2.2 e estamos recebendo um erro ao executar o script de validação, informando que a versão não é compatível com a versão 4.0.9 do SEI.

  Verificamos na documentação disponível no GITHUB e lá aparentemente está descrito que estas versões seriam compatíveis com a 4.0.9 do SEI.
![Screenshot from 2023-03-10 10-45-54](https://user-images.githubusercontent.com/47374057/224332027-dd6d96b0-9ed0-4721-b9af-d30730acea94.png)
 

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Atualize o SEI para a versão 4.0.9
2. Execute os procedimentos de instalação do módulo do PEN
3. Execute o script de verificação de instalação
-----

**Comportamento esperado**
Deveria dar a mensagem de sucesso na verificação

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: 3.2.3 e/ou 3.2.2 (Módulo PEN), 4.0.9 (SEI), Red Hat Linux 8.7
 - Navegador: N/A
 - Perfil do Usuário: N/A
 - Banco de dados: Oracle 11G 
 -----

**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
Atualizar PEN

# /usr/bin/php -c /etc/php.ini /opt/last/sip/scripts/mod-pen/sip_atualizar_versao_modulo_pen.php 2>&1 > sip_versao_modulo_peticionamento.log

Bind:

v1: 3.2.3

v2: VERSAO_MODULO_PEN

00074 - [InfraOracle->executarSql] 1 registro(s) afetado(s)

00075 - [InfraOracle->executarSql] 0.002 s

00076 - TEMPO TOTAL DE EXECUCAO: 0.065 s

00077 - FIM

# /usr/bin/php -c /etc/php.ini /opt/last/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php 2>&1 > sei_versao_modulo_peticionamento.log

Bind:

v1: 3.2.3

v2: VERSAO_MODULO_PEN

00120 - [InfraOracle->executarSql] 1 registro(s) afetado(s)

00121 - [InfraOracle->executarSql] 0.002 s

00122 - TEMPO TOTAL DE EXECUCAO: 0.409 s

00123 - FIM

# /usr/bin/php -c /etc/php.ini /opt/last/sei/scripts/mod-pen/verifica_instalacao_modulo_pen.php

00001 -   INICIANDO VERIFICAÇÃO DA INSTALAÇÃO DO MÓDULO MOD-SEI-PEN:

00002 -     - Arquivos do módulo posicionados corretamente

00003 -     - Módulo corretamente ativado no arquivo de configuracao do sistema

00004 -     - Parâmetros técnicos obrigatórios de integração atribuídos em ConfiguracaoModPEN.php

00005 -     - Certificado digital localizado e corretamente configurado

00006 -     - Conexão com o Barramento de Serviços do PEN realizada com sucesso

00007 -     - Acesso aos dados do Comitê de Protocolo vinculado ao certificado realizado com sucesso

00008 -     - Conexão com o servidor de processamento de tarefas Gearman realizada com sucesso

PHP Fatal error: Uncaught Mdulo Integrao Processo Eletrnico Nacional - PEN (verso 3.2.3) no compatvel com a verso 4.0.9 do SEI.

 thrown in /opt/v409/sei/web/modulos/pen/rn/VerificadorInstalacaoRN.php on line 156

**Comment by rodpinst** [comment]
Prezados identifiquei aqui que no arquivo VerificadorInstalacaoRN.php na lista: 

`const COMPATIBILIDADE_MODULO_SEI = array(
        '3.1.0', '3.1.1', '3.1.2', '3.1.3', '3.1.4', '3.1.5', '3.1.6', '3.1.7', 
        '4.0.0', '4.0.1' , '4.0.2' , '4.0.3', '4.0.4', '4.0.5', '4.0.6', '4.0.7',
        '4.0.3.1', '4.0.3.2', '4.0.3.3', '4.0.3.4', '4.0.3.5'
    );`

Não costa o número da versão 4.0.9 assim como é disponibilizado pelo TRF4 em seu portal para atualização de versões.
![image (1)](https://user-images.githubusercontent.com/47374057/224393863-4a12033c-4e2e-483c-9fa6-a848f0ddb716.png)

**Comment by caduvieira** [comment]
Versão testada e compatível com a versão 3.2.4
