### ISSUE TITLE
Possível bug ao definir contexto - localizacao do certificado digital

### ISSUE THREAD

**Issue by marlinhares** [supergovbr/mod-sei-pen#24]
https://github.com/spbgovbr/mod-sei-pen/blob/9d94acb9f2aea9ca52d330ce7ac582c07eb3918d/tests/funcional/tests/CenarioBaseTestCase.php#L161

Ao definir por exemplo que o arquivo de certificado esteja em /tmp/mycert.pem, no phpunit.xml, acontece erro ao definir pois o teste está adicinando o __DIR__ ao path. Talvez seja melhor retirar e deixar livre.

**Comment by guilhermeadc** [comment]
Problema não ocorre mais demais das atualizações das últimas versões do módulo para SUPER. Organização de parâmetros de testes revisada.
