### ISSUE TITLE
Script de Validaçao de Instalacao está falhando para o SEI 4.0.8 a 4.0.10

### ISSUE THREAD

**Issue by marlinhares** [supergovbr/mod-sei-pen#259]
**Descreva o erro**
Instale o modulo em um SEI 4.0.8, 4.0.9 ou 4.0.10
Rode o script de verifica_instalacao_modulo_pen.php

Vai falhar informando versão incompatível

Os testes funcionais já rodaram para essas versões, portanto pode liberar.

-----

**Para reproduzir**
Ver acima
-----

**Comportamento esperado**
Ver acima

-----

**Screenshots**
NA

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
Ver acima
-----

**Informações adicionais**
Ver acima

-----
**Log de Erros**
Ver acima

**Comment by caduvieira** [comment]
Já foi corrigido versão 3.2.4
