### ISSUE TITLE
Erro de hash no processo 14022.174193/2022-12

### ISSUE THREAD

**Issue by LeandroMedeirosLima** [supergovbr/mod-sei-pen#260]
**Descreva o erro**
Ocorre erro de hash ao se tentar enviar o processo 14022.174193/2022-12 por meio do Tramita.GOV.BR. O erro apresentado é o de Inconsistência identificada no documento de ordem 7 do processo hash de ao menos um componente digital não confere. Porém não houve alteração de ordem dos protocolos.

Ressalta-se que o processo foi enviado em julho/2022 utilizando a **versão do SEI 3.1.7.** 
Por fim, seguem anexos os arquivos utilizados para realizar o comparativo entre os documentos do MEC e do MGI.

**Atualmente, a versão do SEI é a 4.0.8.**

**OBS: A ordem dos documentos não foi alterada.**
**OBS2: Provavelmente alguma alteração no documento devido a versão do SEI( recebido na 3.1.7 e tentativa de envio na 4.0.X).**

**Comment by caduvieira** [comment]
Erros de hash serão tratados pela nova funcionalidade de envio de somente dos arquivos diferentes.
