### ISSUE TITLE
Criar mensagem de erro do script e do verificarDisponibilidade para problema de certificado SSL

### ISSUE THREAD

**Issue by caduvieira** [supergovbr/mod-sei-pen#262]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
A mensagem de erro de falha da cadeia de certificado está genérica. Isso traz dúvida para os usuários

-----

**Descreva a solução que você gostaria**
Separar as mensagem de falha de comunicação com falha na confiança do certificado.

-----

**Descreva alternativas que você considerou**
N/A

-----

**Contexto adicional**
.

**Comment by guilhermeadc** [comment]
Demanda tratara e publicada emergencialmente na versão mod-sei-pen 3.3.0.

> 
_Pull Request será fechado pois foi identificado uma urgência na sua implementação devido ao excesso de demandas de suporte, o que fez a equipe interna da CGSIS implementar e lançar uma versão emergencial do mod-sei-pen 3.3.0._
