### ISSUE TITLE
Uncaught Error: Call to a member function getNumIdLote()

### ISSUE THREAD

**Issue by jair-rfernandes** [supergovbr/mod-sei-pen#265]
**Descreva o erro**
Ao executar manualmente o script de MonitoramentoTarefasPEN o seguinte erro é apresentado:
_

> PHP Fatal error:  Uncaught Error: Call to a member function getNumIdLote() on null in /opt/sei/web/modulos/pen/rn/PenLoteProcedimentoRN.php:116
> Stack trace:
> #0 /opt/sei/web/modulos/pen/rn/ExpedirProcedimentoRN.php(320): PenLoteProcedimentoRN::desbloquearProcessoLoteControlado('1203011')
> #1 /opt/infra/infra_php/InfraRN.php(140): ExpedirProcedimentoRN->expedirProcedimentoControlado(Object(ExpedirProcedimentoDTO))
> #2 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(288): InfraRN->__call('expedirProcedim...', Array)
> #3 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(390): ProcessarPendenciasRN->expedirLote('1203011')
> #4 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(370): PendenciasTramiteRN->enviarPendenciaProcessamentoDireto(Object(PendenciaDTO))
> #5 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(95): PendenciasTramiteRN->enviarPendenciaProcessamento(Object(PendenciaDTO), false)
> #6 /opt/sei/scripts/mod-pen/MonitoramentoTarefasPEN.php(30): PendenciasTramiteRN->encaminharPendencias(false, false, false)
> #7 {main}
>  in /opt/sei/web/modulos/pen/rn/PenLoteProcedimentoRN.php on line 116

_
-----

**Para reproduzir**
_**$php -c /etc/php.ini /opt/sei/scripts/mod-pen/MonitoramentoTarefasPEN.php**_

-----

**Contexto da falha:**
 - Versão do módulo: [ex: 3.2.3]
 - Banco de dados: [SQLServer]

**Comment by pcborges** [comment]
Após testes juntamente com o desenvolvedor @MatheusMarques80 não foi possível reproduzir o erro tanto na versão 3.2.3 do módulo e nem em versões posteriores.
Apesar de a linha apontada pelo erro coincidir com a linha do código na versão 3.2.3 no arquivo /opt/sei/web/modulos/pen/rn/PenLoteProcedimentoRN.php:116 após a execução do trâmite em lote tudo ocorreu bem como demonstrado nas imagens abaixo:

Resultado do script 
![image](https://github.com/supergovbr/mod-sei-pen/assets/3729690/c7b0a22d-f62e-4ac8-a284-b6e7021e878b)

Trâmite no Tramita.gov.br Homologação
![image](https://github.com/supergovbr/mod-sei-pen/assets/3729690/c115401c-3ec6-47ba-8060-1486b5f17b19)

Peço que valide novamente se o erro ainda persiste principalmente em versões mais novas do módulo, e caso permaneça peço que seja reaberta a issue.
