### ISSUE TITLE
Múltiplos envios de um processo por meio do Envio em Lote

### ISSUE THREAD

**Issue by euviniciusmendonca** [supergovbr/mod-sei-pen#267]
**Descreva o erro**
Um processo é enviado inúmeras vezes por meio da funcionalidade Envio em Lote. A cada tentativa é gerado um novo NRE.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para Controle de Processos;
2. Selecione o máximo possível de processos na tela( de preferência processos com arquivos pesados);
3. Clique no Botão Envio Externo de Processo em Lote: 
![image](https://user-images.githubusercontent.com/60577185/233458876-e06e2fdb-406d-4533-9fff-104d1600b769.png)
4. Preencha todos os dados necessários na tela:
![image](https://user-images.githubusercontent.com/60577185/233458632-f6174786-1700-428d-90cf-519269ee2a26.png)
5. Monitore o andamento dos trâmites por meio do Painel de Controle. Abaixo um exemplo de um processo enviado mais de duzentas vezes pelo Envio em Lote:

Em produção: 01250.034484/2018-49

**

![image](https://user-images.githubusercontent.com/60577185/233460410-56a6ebf5-ceea-4a6a-a79f-c083d298d674.png)

**
-----

**Comportamento esperado**
Criar alguma regra para impedir o envio "infinito" de um processo por meio do Envio em Lote.

-----

**Screenshots**
N/A

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: N/A
 - Navegador: N/A
 - Perfil do Usuário: N/A
 - Banco de dados: N/A
-----

**Informações adicionais**
N/A

-----
**Log de Erros**
N/A

**Comment by MatheusMarques80** [comment]
@euviniciusmendonca poderia compartilhar o HTML que foi utilizado no documento?
