### ISSUE TITLE
Melhorar a Mensagem de Recusa Nenhum assunto foi informado

### ISSUE THREAD

**Issue by euviniciusmendonca** [supergovbr/mod-sei-pen#67]
A recusa Nenhum assunto foi informado ocorre no seguinte cenário:

O usuário vincula um tipo de processo na tela Parâmetros de Configuração do Módulo de Tramitações PEN. 

![image](https://user-images.githubusercontent.com/60577185/112893354-f096f180-90b0-11eb-8a9f-059e9097b72f.png)

Caso o usuário não vincule nenhuma sugestão de assunto, quando um órgão envia um processo ao sistema desse usuário o processo é recusado pela mensagem supracitada. 

A implementação que deverá ser feita é melhorar a validação da página de configuração do módulo PEN, validando se o tipo de processo externo selecionado possui o campo "Sugestão de assunto" atribuído. Caso negativo, a seguinte mensagem de validação deve ser lançada ao salvar o cadastro:
"Tipo de processo externo selecionado não possui sugestão de assuntos atribuído."

**Comment by yuribitu** [comment]
Tipo de processo externo selecionado não possui sugestão de assuntos atribuído.

**Comment by mrglaydson** [comment]
Testes realizados na finalização da atividade

[teste issue 67.webm](https://user-images.githubusercontent.com/11926294/209930540-e23eeb86-114e-41dc-aa15-668e91f988c8.webm)

**Comment by higodf** [comment]
Não foi identificado um PR ativo para validação.

**Comment by mrglaydson** [comment]
Segue PR correto com a realização da tarefa: https://github.com/supergovbr/mod-sei-pen/pull/235
