### ISSUE TITLE
Melhoria da Mensagem - Alteração na Ordem de Documentos do Processo

### ISSUE THREAD

**Issue by euviniciusmendonca** [supergovbr/mod-sei-pen#81]
A minha sugestão de redação é a seguinte:

A ordem de documentos foi alterada. Verifique a ordem original dos documentos e tente novamente !!

**Se possível colocar mais alguma informação indicando qual documento ou quais documentos foi/ foram retirados da ordem original.**

**Exemplo:**
![c293a3b3-e815-44a6-85a2-352f36176059](https://user-images.githubusercontent.com/60577185/116614165-f3833d00-a90f-11eb-9fea-77109128ce4f.jpg)

**Comment by guilhermeadc** [comment]
Demanda vinculada à issue #13

**Comment by yuribitu** [comment]
Regras para identificação e tratamento de erros causados pela mudança da ordem de documentos na árvores do processo
1. Identificar se houve erro no envio do processo por motivo de erros no hash (Vide imagem acima);
2. Verificar se o processo havia sido tramitado anteriormente, caso negativo desconsiderar o tratamento da mensagem;
3. Verificar se houve mudança na ordem dos documentos pela tabela de histórico do processso (ATIVIDADE) e também pela tabela de relacionamento de protocolos (REL_PROTOCOLO_PROTOCOLO).

**Comment by yuribitu** [comment]
Trocar o final da frasse:
De: "hash de ao menos um componente digital não confere"
Para: "a ordem dos documentos foram modificadas na árvore do processo"

**Comment by guilhermeadc** [comment]
Necessário atualizar último Pull Request com as alterações solicitadas na última reunião, ou seja, a validação deveria ocorrer somente em caso de erro de hash ao enviar o processo, que que a validação antecipada não é possível por gerar falhas de falso-positivo.

Pull Request mencionado nesta demanda para testes encontra-se desatualizado: https://github.com/supergovbr/mod-sei-pen/pull/202

**Comment by Mauro1706** [comment]
Foi alterado no commit Cantoni

**Comment by guilhermeadc** [comment]
Solicitação de melhoria na implementação para incluir maiores informações sobre a mudança de ordem aplicada. Na implementação atual, em revisão, não foi citado a necessidade de informar a ordem do documento que foi modificada. Avaliando melhor a necessidade do usuário, foi identificado que a ordem é fundamental estar na mensagem para que o mesmo possa fazer as devidas correções.

Com isto, iremos retornar esta issue para o backlog para implementação desta melhoria.

**Comment by guilhermeadc** [comment]
Nâo foi possível aceitar o merge pois o Pull Request está com inúmeros problemas de encode de caracteres (deve ser usado isso), quebra nas acentuações das palavras dos arquivos modificados, e diferença em relação ao carácter de quebra de linha.

Revisar as configurações da IDE de desenvolvimento utilizada e avaliar o uso dos padrões utilizados pelo sistema:
- ISO8859-1
- Quebra de linha: LF (Linux).Não utilizar a quebra do windows (Windows: CRLF)

No mais, a implementação parece estar funcionando adequadamente, conforme solicitado.

**Comment by euviniciusmendonca** [comment]
"Não foi possível enviar o processo <Nº do Processo> por meio do Tramita.GOV.BR, em decorrência de alteração da ordem de um ou mais documentos na árvore do processo.

 

A seguir, a lista dos documentos com ordem alterada:

 

A ordem do documento XXXXX foi modificada na árvore do processo, mudando da posição 99 para a posição 55.
A ordem do documento XXXXX foi modificada na árvore do processo, mudando da posição 99 para a posição 55.
.
.
.
.

Sugere-se desfazer as alterações acima listadas antes de realizar nova tentativa de trâmite.


Mantenha sempre a ordem original dos documentos de processos recebidos pelo Tramita.GOV.BR, uma vez que sua instrução foi realizada por outro órgão. Tenha em mente que qualquer alteração nessa ordem pode impedir um novo trâmite do processo."

**Comment by euviniciusmendonca** [comment]
Solicita-se o vídeo como evidência da melhoria !!!
